DEBUG: false

MODEL:
  name: "deeplabv3_resnet50_nopretrain"
  pretrained_weight: null
TRAIN:
  epochs: 30
  learning_rate: 0.00008
  gpu_id: 3
  num_workers: 2
  momentum: 0.9
  weight_decay: 1e-4
  batch_size: 3
VAL:
  num_workers: 2
